export const ERROR_MESSAGES = {
   NO_FILE_UPLOAD: 'NO FILE UPLOAD',
}
export const RESPONSE_MESSAGE = {
  FILE_UPLOAD_SUCCESSFULLY: 'File uploaded successfully',
  SEND_EMAIL_VERIFY_SUCCESSFULLY: 'Send email verify successfully',
  PRODUCT_CREATED_SUCCESSFULLY: 'Product created successfully',
  FETCH_ALL_PRODUCTS_BY_PAGINATION: 'Fetch all products by pagination successfully',
  GET_PRODUCT_DETAIL: 'Get product detail successfully',
  PRODUCT_UPDATED_SUCCESSFULLY: 'Product updated successfully',
  SEARCH_PRODUCT_BY_KEYWORD: 'Search product by keyword successfully',
  PRODUCT_DELETED_SUCCESSFULLY: 'Product deleted successfully',
  USER_CREATED_SUCCESSFULLY: 'User created successfully',
  GET_ALL_USERS_SUCCESS: 'Get all users success',
  GET_USER_BY_ID_SUCCESS: 'Get user by id success',
  USER_UPDATED_SUCCESSFULLY: 'User updated successfully',
  USER_DELETED_SUCCESSFULLY: 'User deleted successfully',
  USER_BANNED_SUCCESSFULLY: 'User banned successfully',
  USER_UNBANNED_SUCCESSFULLY: 'User unbanned successfully',
  FETCH_ALL_CATEGORIES_SUCCESS: 'Fetch all categories success',
  GET_CATEGORY_BY_ID_SUCCESS: 'Get category by id success',
  UPDATE_CATEGORY_SUCCESS: 'Update category successfully',
  DELETE_CATEGORY_SUCCESS: 'Delete category successfully',
  CREATE_CATEGORY_SUCCESS: 'Create category successfully',
  GET_ALL_CATEGORIES_SUCCESS: 'Get all categories success',
  LOGIN_SUCCESS: 'Login successfully',
  GET_USER_INFORMATION: 'Get user information successfully',
  REGISTER_SUCCESS: 'Register successfully',
  LOGOUT_SUCCESSFULLY: 'Logout successfully',
  GET_USER_BY_REFRESH_TOKEN: 'Get user by refresh token successfully',
  VERIFY_EMAIL: 'Verify email successfully',
  FORGOT_PASSWORD: 'Forgot password successfully',
  PASSWORD_HAS_BEEN_SUCCESSFULLY_RESET: 'Password has been successfully reset',
}